[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
extend-select = ["E501", "I"]

[tool.ruff.lint.isort]
combine-as-imports = true
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
